version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/crud
    depends_on:
      - mongodb

volumes:
  mongo-data: